export const PAGE_LABELS = {
  Dashboard: 'Dashboard',
  MarketNews: 'Mercado',
  Vendas: 'Vendas',
  MeusClientes: 'Agenda do Dia',
  CentralLeads: 'Central de Leads',
  Contratos: 'Contratos',
  Implantacoes: 'Implantações',
  Pipeline: 'Pipeline',
  Precificacao: 'Precificação',
  Desempenho: 'Desempenho',
  Clientes: 'Clientes',
  Vendedores: 'Vendedores',
  Espelhamentos: 'Indicadores',
  ChatPage: 'Chat Interno',
  RelatorioInteracoes: 'Rel. Interações',
  Manual: 'Manual',
  Treinamento: 'Capacitação',
  Suporte: 'Suporte',
  Comissoes: 'Comissões',
  Notificacoes: 'Notificações',
  Comunicados: 'Comunicados',
  NotasFiscais: 'Notas Fiscais',
  TreinamentoAdmin: 'Capacitação (Admin)',
  RelatorioComissoes: 'Rel. Comissões',
  Leads: 'Prospecção',
  Metas: 'Metas',
  Produtos: 'Produtos',
  Importar: 'Importar',
  Usuarios: 'Usuários',
  DashParceiro: 'Dash Parceiro',
  AssistenteTreinamentos: 'Assistente',
};

export const getPageLabel = (page) => PAGE_LABELS[page] || page;